"use client"

import { useState, useRef } from "react"
import { ChevronDown } from "lucide-react"

export default function FAQ() {
  const categories = [
    {
      title: "General Questions",
      faqs: [
        {
          question: "What is the AANR TRACER Application?",
          answer:
            "The AANR Technology Readiness Assessment for Commercialization Enhancement and Roadmapping (TRACER) Application is a web-based assessment and recommendation-support tool designed to evaluate the Technology Readiness Level (TRL) of innovations in the Agriculture, Aquatic, and Natural Resources (AANR) sector. It helps users understand the maturity of their technology and identify next steps toward commercialization, adoption, or utilization.",
        },
        {
          question: "Who can use the TRACER Application?",
          answer:
            "The application is intended for:\n- Researchers and innovators in the AANR sector\n- Technology transfer offices and commercialization units\n- Academic, research, and government institutions\n- Organizations supporting innovation, incubation, and technology adoption",
        },
        {
          question: "Do we need to log into the system or create an account to use the TRACER Application?",
          answer:
            "No. The user does not need any log-in credentials to access and use the application.",
        },
        {
          question: "Is the AANR TRACER Application free to use?",
          answer:
            "Yes. The AANR TRACER App is free to use and accessible to anyone through desktop, laptop, or any mobile device using any browser.",
        },
        {
          question: "Will the FAQs be updated?",
          answer:
            "Yes. This FAQ section may be updated periodically to reflect system enhancements, policy updates, or user feedback. Users are advised to refer to the latest version available on the website.",
        },
      ],
    },
    {
      title: "Technology Assessment",
      faqs: [
        {
          question: "What types of technologies can be assessed?",
          answer:
            "AANR TRACER is suitable for technologies that:\n- Fall under the Agriculture, Aquatic, and Natural Resources (AANR) sector\n- Intended for commercial purposes using common modes of commercialization such as licensing through a spinoff, direct licensing, joint venture, profit sharing, or buy-out",
        },
        {
          question: "How does the TRACER Application determine the TRL?",
          answer:
            "The application encrypted a structured readiness assessment framework based on the NASA TRL, adapted for applicability to AANR technologies, the DOST–PCAARRD assessment framework, and expert experience in research and development (R&D) and commercialization that has undergone intensive review by subject-matter experts and experienced researchers across various commodities and consultations with personnel directly involved in technology transfer programs of the Consortia Member Institutions (CMIs) under the RAISE Program.",
        },
        {
          question: "Are the TRL results final and absolute?",
          answer:
            "No. The TRL results generated by the AANR TRACER Application are indicative and apply only to the technology assessed. Results are entirely based on the accuracy and completeness of the information provided by the user at the time of the assessment.",
        },
        {
          question: "What happens if incomplete or incorrect information is entered?",
          answer:
            "Incomplete, incorrect, or misleading information may result in inaccurate TRL classification, gap identification, or recommendations. Users are responsible for ensuring that all information entered into the system is accurate and complete.\nThe developers shall not be liable for any errors or misclassifications resulting from such inputs.",
        },
        {
          question: "Does the system verify or validate the information provided?",
          answer:
            "No. The AANR TRACER Application does not independently verify or validate user-provided information. All assessments and recommendations are generated solely based on the data entered by the user.",
        },
      ],
    },
    {
      title: "Gaps and Recommendations",
      faqs: [
        {
          question: "How are gaps and recommendations generated?",
          answer:
            "The identified gaps and system-generated recommendations are produced through AI-driven analysis aligned with the technology assessment module from the structured readiness assessment framework encrypted in the application. These recommendations are indicative and intended to support planning and decision-making.",
        },
        {
          question: "Are the recommendations mandatory to follow?",
          answer:
            "No. The recommendations are not prescriptive or mandatory. They are provided as guidance to help users understand potential next steps and areas for improvement.",
        },
      ],
    },
    {
      title: "Data & Results",
      faqs: [
        {
          question: "Is my data saved in the system?",
          answer:
            "No. The handling of assessment data depends on the user actions. Saving or sharing of the results generated during the assessment session is optional and subject to user discretion. Data saving will only occur if the user opts to save the generated result by downloading the pdf copy in the device used during the assessment or the user sends the pdf copy of the result through an email address.",
        },
        {
          question: "Can I download or export my assessment results?",
          answer:
            "Yes. The application allows users to review, share, download or export assessment summaries and results for internal use, reporting, or strategic planning in a pdf file only.",
        },
        {
          question: "Can I assess more than one technology?",
          answer:
            "Yes. Users may conduct multiple assessments for different technologies, provided each assessment is completed separately with accurate and relevant information for each technology.",
        },
        {
          question: "How long does it take to complete an assessment?",
          answer:
            "The time required depends on the complexity of the technology and the availability of information. On average, completing an assessment may take 10 minutes once all required details are prepared.",
        },
        {
          question: "Who should I contact for technical or methodological support?",
          answer:
            "For technical assistance or clarification on assessment methodology, users are encouraged to contact their institutional technology transfer office or refer to the support and reference materials provided on the AANR TRACER Application website.",
        },
      ],
    },
  ]

  const [openIndex, setOpenIndex] = useState<{ [key: string]: number | null }>({})
  const refs = useRef<{ [key: string]: HTMLDivElement | null }>({})

  const toggleFAQ = (category: string, index: number) => {
    setOpenIndex((prev) => ({
      ...prev,
      [category]: prev[category] === index ? null : index,
    }))
  }

  const scrollToCategory = (categoryTitle: string) => {
    refs.current[categoryTitle]?.scrollIntoView({ behavior: "smooth", block: "start" })
  }

  return (
    <div className="bg-[var(--bg-color-light)] text-gray-800">

      {/* ================= HERO ================= */}
      <section className="w-full bg-[var(--secondary-color)] text-white py-24 px-6">
        <div className="max-w-6xl mx-auto text-center">
          <h1 className="text-4xl md:text-5xl font-bold mb-6">
            Frequently Asked Questions(FAQs)
          </h1>
          <p className="text-lg md:text-xl text-gray-200 max-w-3xl mx-auto">
            Learn more about AANR TRACER and how it supports technology readiness assessment.
          </p>
        </div>
      </section>

      {/* ================= CATEGORY FILTER ================= */}
      <section className="py-10 px-6 lg:px-20">
        <div className="max-w-6xl mx-auto flex flex-wrap gap-4 justify-center">
          {categories.map((category, idx) => (
            <button
              key={idx}
              onClick={() => scrollToCategory(category.title)}
              className="
                bg-[var(--secondary-color)] 
                text-white 
                font-semibold 
                px-4 py-2 
                rounded-full 
                transition 
                transform 
                hover:bg-opacity-80 
                hover:scale-105 
                hover:shadow-lg
              "
            >
              {category.title}
            </button>
          ))}
        </div>
      </section>

      {/* ================= FAQ LIST ================= */}
      <section className="py-20 px-6 lg:px-20">
        <div className="max-w-4xl mx-auto space-y-12">
          {categories.map((category, cidx) => (
            <div
              key={cidx}
              ref={(el) => {
                refs.current[category.title] = el ?? null
              }}
              className="scroll-mt-20"
            >
              <h2 className="text-2xl font-bold text-[var(--secondary-color)] mb-6">
                {category.title}
              </h2>
              <div className="space-y-6">
                {category.faqs.map((faq, fidx) => (
                  <div
                    key={fidx}
                    className="bg-white rounded-2xl shadow-md border border-gray-100"
                  >
                    <button
                      onClick={() => toggleFAQ(category.title, fidx)}
                      className="w-full flex justify-between items-center p-6 text-left"
                    >
                      <span className="font-semibold text-lg">{faq.question}</span>
                      <ChevronDown
                        size={20}
                        className={`transition-transform duration-300 ${
                          openIndex[category.title] === fidx ? "rotate-180" : ""
                        }`}
                      />
                    </button>

                    {openIndex[category.title] === fidx && (
                      <div className="px-6 pb-6 text-gray-600 whitespace-pre-line leading-7">
                        {faq.answer}
                      </div>
                    )}
                  </div>
                ))}
              </div>
            </div>
          ))}
        </div>
      </section>
    </div>
  )
}