// The disclaimer text block with inline tooltips.
// Accepts no props — content is static and lives in disclaimerTooltips.ts.

import { Tooltip }               from "@/components/ui/ToolTip";
import { DISCLAIMER_TOOLTIPS }   from "@/constants/disclaimerToolTips";

export function DisclaimerCard() {
  return (
    <div className="bg-[var(--color-bg-card)] border border-[var(--color-border)] rounded-2xl overflow-hidden mb-6 shadow-[0_4px_24px_rgba(15,46,26,0.06)]">
      {/* Header */}
      <div className="flex items-center gap-2.5 px-7 py-4 border-b border-[#f5f2ec] bg-[var(--color-bg-subtle)]">
        <span className="w-2 h-2 rounded-full bg-[var(--color-accent)] flex-shrink-0" />
        <span className="text-[11px] font-bold tracking-[2px] uppercase text-[var(--color-accent)]">
          AANR TRACER · Disclaimer
        </span>
      </div>

      {/* Body */}
      <div className="px-7 py-10 flex flex-col gap-5">

        {/* Paragraph 1 */}
        <p className="text-[15px] leading-[1.85] text-[var(--color-text-gray)] font-light text-justify">
          The Technology Readiness Assessment for Commercialization Enhancement and Roadmapping (TRACER) Application
          is specifically designed for{" "}
          <strong className="font-semibold italic">
            Agriculture, Aquatic, and Natural Resources (AANR) technologies intended for{" "}
            <Tooltip text={DISCLAIMER_TOOLTIPS.commercialization}><b>commercialization</b></Tooltip>
          </strong>.
          The TRACER level generated by the system applies only to the technology assessed and is based entirely on
          the accuracy and completeness of the information provided by the user. The developers shall not be liable
          for any errors, inaccuracies, or misclassifications resulting from incomplete, incorrect, or misleading
          data entered into the system.
        </p>

        {/* Paragraph 2 */}
        <p className="text-[15px] leading-[1.85] text-[var(--color-text-gray)] font-light text-justify">
          Technologies transferred through{" "}
          <Tooltip text={DISCLAIMER_TOOLTIPS.extension}>extension</Tooltip>,{" "}
          <Tooltip text={DISCLAIMER_TOOLTIPS.deployment}>deployment</Tooltip>, or{" "}
          <Tooltip text={DISCLAIMER_TOOLTIPS.otherModes}>other non-commercialization</Tooltip>{" "}
          modes are not eligible for assessment using this application.
        </p>

        {/* Paragraph 3 */}
        <p className="text-[15px] leading-[1.85] text-[var(--color-text-gray)] font-light text-justify">
          The TRACER level generated by the system applies only to the specific technology assessed and is based
          entirely on the accuracy and completeness of the information provided by the user. The developers shall
          not be liable for any errors, inaccuracies, or misclassifications resulting from incomplete, incorrect,
          or misleading data entered into the system.
        </p>

        <div className="h-px bg-[#f0ece3]" />

        {/* Paragraph 4 */}
        <p className="text-[15px] leading-[1.85] text-[var(--color-text-gray)] font-light text-justify">
          Furthermore, the identified gaps and system-generated recommendations are produced through AI-driven
          analysis aligned with the Technology Readiness Level (TRL) definitions referenced and made available
          within this application.
        </p>

      </div>
    </div>
  );
}