"use client";

import { useState } from "react";
import { useRouter } from "next/navigation";

export default function Disclaimer() {
  const [agreed, setAgreed] = useState(false);
  const router = useRouter();

  const handleProceed = () => {
    router.push("/assessment/data-privacy");
  };

  return (
    <div className="bg-[var(--bg-color-light)] min-h-screen py-10 px-6 lg:px-20 text-gray-800 flex flex-col justify-center">
      
      {/* ===== Heading ===== */}
      <section className="max-w-4xl mx-auto">
        <h1 className="text-center text-4xl md:text-5xl font-bold text-[var(--secondary-color)] mb-12">
          DISCLAIMER
        </h1>

        {/* ===== Intro Notice ===== */}
        <div className="bg-yellow-50 border-l-4 border-yellow-400 p-6 rounded-lg mb-10 shadow-sm">
          <p className="text-justify text-gray-800 italic">
            Please read the following important information about this AANR TRACER App before you proceed with the assessment.
          </p>
        </div>

        {/* ===== Main Disclaimer ===== */}
        <div className="space-y-8 mb-10">
          <p className="text-justify text-gray-700 leading-relaxed">
            This Technology Readiness Assessment for Commercialization Enhancement and Roadmapping (TRACER) Application is 
            specifically designed for <b><i>AANR technologies intended for commercialization</i></b>. The Technology Readiness Level (TRL) 
            results generated by the system apply only to the technology assessed and are based entirely on the accuracy and 
            completeness of the information provided by the user. The developers shall not be liable for any errors, inaccuracies, 
            or misclassifications resulting from incomplete, incorrect, or misleading data entered into the system.
          </p>

          <p className="text-justify text-gray-700 leading-relaxed">
            Furthermore, the identified gaps and system-generated recommendations are produced through AI-driven analysis aligned 
            with the TRL definitions referenced and made available on this website.
          </p>

          <p className="text-justify text-gray-700 leading-relaxed">
            To determine whether your technology is appropriate for use with this tool, please refer to the User Manual.
          </p>
        </div>

        {/* ===== Checkbox & Proceed Button ===== */}
        <div className="flex flex-col items-center space-y-6">
          <label className="flex items-center space-x-3 cursor-pointer mb-5">
            <input 
              type="checkbox" 
              checked={agreed} 
              onChange={(e) => setAgreed(e.target.checked)}
              className="w-5 h-5 text-[var(--secondary-color)] border-gray-300 rounded focus:ring-[var(--secondary-color)]"
            />
            <span className="text-gray-700">
              I have read and understood the information above 
            </span>
          </label>

          <button
            onClick={handleProceed}
            disabled={!agreed}
            className={`px-10 py-3 rounded-3xl font-semibold text-white shadow-lg transition-all duration-300
              ${agreed 
                ? "bg-[var(--secondary-color)] hover:scale-105 hover:shadow-2xl" 
                : "bg-gray-400 cursor-not-allowed"
              }`}
          >
            Next
          </button>
        </div>
      </section>
    </div>
  );
}