export const categoryOrder = [
  "Technology Status",
  "Market and Commercialization Status",
  "Intellectual Property Protection Status",
  "Industry Adoption Status",
  "Regulatory Compliance Status",
];

export const categoryDescriptions: Record<string, string> = {
  "Technology Status":
    "Assess where your technology stands in terms of development, functionality, and readiness for real-world use.",
  "Market and Commercialization Status":
    "Evaluate how prepared your technology is to enter the market and meet customer needs.",
  "Intellectual Property Protection Status":
    "Review the protections in place for your innovation, such as patents and trademarks.",
  "Industry Adoption Status":
    "Check how your technology is being accepted and used within your target industry or sector.",
  "Regulatory Compliance Status":
    "Ensure your technology meets all necessary legal and industry standards for safety and quality.",
};

export const trlLevels = [
  { n: 1, label: "Concept & Market Definition",                     w: "w-[11%]",  color: "bg-slate-400" },
  { n: 2, label: "Design / Formulation / Prototype Planning",       w: "w-[22%]",  color: "bg-slate-500" },
  { n: 3, label: "Prototype Development & Laboratory Testing",      w: "w-[33%]",  color: "bg-amber-400" },
  { n: 4, label: "Controlled Validation & IP Filing",               w: "w-[44%]",  color: "bg-orange-400" },
  { n: 5, label: "Pilot Testing & Industry Engagement",             w: "w-[55%]",  color: "bg-emerald-400" },
  { n: 6, label: "Multi-location Testing & Scale-up Preparation",   w: "w-[66%]",  color: "bg-cyan-400" },
  { n: 7, label: "Industry Validation & Regulatory Submission",     w: "w-[77%]",  color: "bg-blue-400" },
  { n: 8, label: "Commercial Production Readiness",                 w: "w-[88%]",  color: "bg-violet-400" },
  { n: 9, label: "Full Commercialization",                          w: "w-full",   color: "bg-green-400" },
];

export const TRACER_LEVELS = [
  {
    level: 1,
    consolidated: "Concept & Market Definition",
    food: "Concept & Market Definition",
    animalFeed: "Concept & Industry Relevance",
    fertilizer: "Concept & Target Definition",
    machinery: "Concept & User Identification",
    device: "Concept & Industry Definition",
    ict: "Concept & Industry Definition",
    naturalResourceMaterials: "Concept & Material Definition",
    plantVarietyConventional: "Concept & Market Definition",
    plantVarietyGeneEdited: "Concept & Target Definition",
    animalBreed: "Concept & Market Definition",
  },
  {
    level: 2,
    consolidated: "Design / Formulation / Prototype Planning",
    food: "Laboratory Formulation",
    animalFeed: "Laboratory Formulation",
    fertilizer: "Laboratory Formulation",
    machinery: "Design & Prototype Development",
    device: "Initial Prototype Development",
    ict: "System Design & Initial Development",
    naturalResourceMaterials: "Formulation & Preliminary Assessment",
    plantVarietyConventional: "Germplasm Collection & Breeding Planning",
    plantVarietyGeneEdited: "Germplasm & Molecular Planning",
    animalBreed: "Parent Selection & Breeding Planning",
  },
  {
    level: 3,
    consolidated: "Prototype Development & Laboratory Testing",
    food: "Optimization & Technical Characterization",
    animalFeed: "Feeding Trial & Optimization",
    fertilizer: "Laboratory Efficacy & Safety Testing",
    machinery: "Functional Testing",
    device: "Laboratory Refinement & Analytical Verification",
    ict: "Integrated Prototype Development",
    naturalResourceMaterials: "Laboratory Sample Production & Testing",
    plantVarietyConventional: "Initial Crosses & Screening",
    plantVarietyGeneEdited: "Laboratory Gene Editing & Design",
    animalBreed: "Initial Breeding & Screening",
  },
  {
    level: 4,
    consolidated: "Controlled Validation & IP Filing",
    food: "Controlled Validation & IP Filing",
    animalFeed: "Nutritional & Safety Validation & IP Filing",
    fertilizer: "Controlled Validation & IP Filing",
    machinery: "Controlled Operational Validation & IP Filing",
    device: "Controlled Validation & IP Filing",
    ict: "Alpha Testing & Market Positioning & IP Filing",
    naturalResourceMaterials: "Controlled Validation & IP Filing",
    plantVarietyConventional: "Controlled Growth & Trait Confirmation",
    plantVarietyGeneEdited: "Regeneration & Preliminary Phenotyping",
    animalBreed: "Controlled Growth & Trait Confirmation",
  },
  {
    level: 5,
    consolidated: "Pilot Testing & Industry Engagement",
    food: "Pilot Preparation",
    animalFeed: "Pilot Preparation",
    fertilizer: "Pilot Preparation",
    machinery: "Pilot Operation",
    device: "Pilot Testing & Industry Engagement",
    ict: "Beta Testing & Industry Engagement",
    naturalResourceMaterials: "Pilot Production & Promotion",
    plantVarietyConventional: "Line Selection & Preliminary Field Trials",
    plantVarietyGeneEdited: "Contained Field Trials & Regulatory Preparation",
    animalBreed: "Line Selection & Preliminary Trials",
  },
  {
    level: 6,
    consolidated: "Multi-location Testing & Scale-up Preparation",
    food: "Pilot Production & Market Exposure",
    animalFeed: "Pilot Production & Industry Testing",
    fertilizer: "Pilot Production & Field Testing",
    machinery: "Field Testing & Certification Preparation",
    device: "Multi-location Testing & Manufacturing Preparation",
    ict: "Initial Industry Deployment",
    naturalResourceMaterials: "Prototype Application & Feedback",
    plantVarietyConventional: "Multi-location Trials & Industry Engagement",
    plantVarietyGeneEdited: "Multi-location Trials & Industry Feedback",
    animalBreed: "Multi-location Trials & Industry Feedback",
  },
  {
    level: 7,
    consolidated: "Industry Validation & Regulatory Submission",
    food: "Industry Validation & Regulatory Preparation",
    animalFeed: "Industry Validation & Regulatory Preparation",
    fertilizer: "Industry Validation & Regulatory Preparation",
    machinery: "Industry Validation & Replication",
    device: "Industry Validation & Regulatory Preparation",
    ict: "Industry Validation & Regulatory Preparation",
    naturalResourceMaterials: "Field Testing & Standardization",
    plantVarietyConventional: "Commercial Protocol & Regulatory Submission",
    plantVarietyGeneEdited: "Commercial Protocol & Regulatory Submission",
    animalBreed: "Commercial Protocol & Regulatory Submission",
  },
  {
    level: 8,
    consolidated: "Commercial Production Readiness",
    food: "Commercial Production Readiness",
    animalFeed: "Commercial Production Readiness",
    fertilizer: "Commercial Production Readiness",
    machinery: "Commercial Production Readiness",
    device: "Commercial Production Readiness",
    ict: "Commercial Production Readiness",
    naturalResourceMaterials: "Commercial-Scale Validation",
    plantVarietyConventional: "Industry-Scale Production & Registration",
    plantVarietyGeneEdited: "Industry-Scale Production & Registration",
    animalBreed: "Industry-Scale Breeding & Regulatory Compliance",
  },
  {
    level: 9,
    consolidated: "Full Commercialization",
    food: "Full Commercialization",
    animalFeed: "Full Commercialization",
    fertilizer: "Full Commercialization",
    machinery: "Full Commercialization",
    device: "Full Commercialization",
    ict: "Full Commercialization",
    naturalResourceMaterials: "Full Commercialization",
    plantVarietyConventional: "Full Commercialization",
    plantVarietyGeneEdited: "Full Commercialization",
    animalBreed: "Full Commercialization",
  }
];